app/Services/Doctor/VaccinationSlotService.cs
app/backend.csproj

Removed Entity Framework 6.
We are using Entity Framework Core.

SP-115 Remove EF6

---

tests/Helpers/DbHelper.cs
tests/Unit/Middleware/JwtMiddlewareTest.cs
tests/Unit/Services/Doctor/DoctorAuthServiceTest.cs
tests/Unit/Services/Doctor/VaccinationSlotServiceTest.cs

Dodałem unit testy do dodawanie slotów.
Próbowałem dodać unit testy to AuthorizeAttribute ale niestety nie byłem w stanie bo parametru AuthorizationFilterContext context nie da się zmockować a nie mogłem utworzyć jakiegoś pustego obiektu bo cały czas coś się czepiał Visual

Feature/SP-108 - Unit testy dodawania slotów

---

app/Controllers/Doctor/VaccinationSlotsController.cs
app/Dto/Requests/Doctor/VaccinationSlot/FilterVaccinationSlotsRequest.cs
app/Dto/Requests/Doctor/VaccinationSlot/NewVaccinationSlotRequest.cs
app/Dto/Responses/Doctor/VaccinationSlot/NewVaccinationSlotResponse.cs
app/Dto/Responses/Doctor/VaccinationSlot/VaccinationSlotResponse.cs
app/Dto/Responses/PaginatedResponse.cs
app/Dto/Responses/SuccessResponse.cs
app/Exceptions/BasicException.cs
app/Exceptions/ConflictException.cs
app/Exceptions/NotFoundException.cs
app/Helpers/PaginatedList.cs
app/Postman/IO.postman_collection.json
app/Services/Doctor/VaccinationSlotService.cs
tests/Helpers/DbHelper.cs
tests/Unit/Services/Doctor/VaccinationSlotServiceTest.cs

Add:
- Endpoint for showing vaccination slots for doctor (with pagination, filtering by only reserve and start/end date)
- Endpoint for deleting (only not reserved) vaccination slots
- Test for new features

[SP-118] Vaccination slots list (with deleting)

---

app/Exceptions/ValidationException.cs
app/Services/Doctor/VaccinationSlotService.cs
tests/Unit/Services/Doctor/VaccinationSlotServiceTest.cs

- Added date validation against date in the past.
- Introduced more descriptive error messages.

[SP-122] Improvements for adding vaccination slots

---

app/Controllers/Patient/PatientRegistationController.cs
app/Dto/Requests/Patient/PatientRegistrationAddressRequest.cs
app/Dto/Requests/Patient/PatientRegistrationRequest.cs
app/Helpers/EnumberableExtensions.cs
app/Helpers/PeselValidator.cs
app/Models/Accounts/PatientModel.cs
app/Postman/IO.postman_collection.json
app/Program.cs
app/Services/Admin/AdminDoctorsService.cs
app/Services/Doctor/VaccinationSlotService.cs
app/Services/Patient/PatientRegistrationService.cs

Patient registration
- Checking if provided e-mail or PESEL already exists.
- Validating PESEL checksum.

[SP-20] Patient registration

---

app/Database/Seeder.cs
app/Dto/Responses/PaginatedResponse.cs
app/Models/Visits/VaccinationSlotModel.cs
app/Program.cs
app/Validators/Requests/Doctor/VaccinationSlot/FilterVaccinationSlotValidator.cs
app/backend.csproj

- Przerobiłem response tak żeby informacje o paginacji były w osobnych obiekcie (pagination)
- dodałem seeder do slotów
- dodałem fluent-validation (tam będziemy tworzyć klasy o takiej samej hierarchii jak requesty i zapisywać walidację pól)

[SP-131] Poprawki do endpointa z vaccination-slots

---

app/Controllers/Admin/AdminDoctorsController.cs
app/Dto/Requests/Doctor/VaccinationSlot/FilterVaccinationSlotsRequest.cs
app/Dto/Requests/PaginationRequest.cs
app/Dto/Responses/Doctor/DoctorResponse.cs
app/Models/Accounts/PatientModel.cs
app/Postman/IO.postman_collection.json
app/Services/Admin/AdminDoctorsService.cs
tests/Unit/Services/Admin/AdminDoctorsServiceTest.cs

[SP-134] added GET admin -> doctor / doctors

---

app/Database/DataContextExtensions.cs
app/backend.csproj

(IsDeleted in DoctorModel has virtual accessors)

quick fix for LoadFields

---

app/Controllers/Patient/VaccinationController.cs
app/Postman/IO.postman_collection.json
app/Services/BugService.cs
app/Services/Patient/VaccinationService.cs
app/appsettings.json
tests/Helpers/DbHelper.cs
tests/Unit/Services/Patient/VaccinationServiceTest.cs

Added canceling vaccination visit with task email sending (fully asynch).
Added unit testing for vaccination canceling

[SP-28] Added canceling vaccination visit with testing

---

app/Controllers/Admin/AdminPatientController.cs

[SP-151] Discrepancy with our API regarding Admin/getPatients

---

app/Services/Doctor/VaccinationSlotService.cs

[SP-152] Doctor / deleteSlot proxy error fix

---

app/Controllers/Patient/VaccinationController.cs
app/Helpers/Mailer.cs
app/Services/BugService.cs
app/Services/Patient/VaccinationService.cs
tests/Unit/Services/BugServiceTest.cs
tests/Unit/Services/Patient/VaccinationServiceTest.cs

we need to be able to process a comma separated list of vaccines

[SP-153] incompatible API endpoint patient/show available vaccines

---

app/Dto/Responses/Doctor/Vaccination/VaccinationSlotResponse.cs

[SP-156] return null instead of {} if vaccination is null

---

app/Dto/Responses/Doctor/Vaccination/VaccinationSlotResponse.cs
app/Dto/Responses/Patient/Vaccination/AvailableSlotResponse.cs
tests/Unit/Services/Patient/VaccinationServiceTest.cs

Added converting to universal time in response

[SP-165] Universal time

---

app/appsettings.json

Changed e-mail account settings to newly created Mailtrap account.

[SP-178] Change to common mailtrap account

---

app/Controllers/Patient/VaccinationController.cs
app/Helpers/CertificateGenerator.cs
app/Postman/IO.postman_collection.json
app/Services/Patient/VaccinationService.cs
app/backend.csproj
tests/backend-tests.csproj

Added generation of vaccination certificate in PDF format.
Updated Postman collection - it's possible to see preview of response inside Postman.
**Sample certficate:**
[Sample Certificate.pdf](https://github.com/szczepienia-pw/backend/files/8548123/Sample.Certificate.pdf)
Currently certificate does not contain QR code. Due to issues regarding limitations of .NET 6.0 (lack of System.Drawing) and poor support from QR code libraries, I've decided to handle it as a separate task.

[SP-30] Download vaccine certificate

---

app/Controllers/Doctor/VaccinationSlotsController.cs
app/Dto/Requests/Doctor/VaccinationSlot/VaccinatePatientRequest.cs
app/Models/Vaccines/DiseaseEnum.cs
app/Models/Visits/StatusEnum.cs
app/Postman/IO.postman_collection.json
app/Services/Doctor/VaccinationSlotService.cs
app/Services/Patient/VaccinationService.cs
tests/Helpers/DbHelper.cs
tests/Unit/Services/Doctor/VaccinationSlotServiceTest.cs
tests/Unit/Services/Patient/VaccinationServiceTest.cs

- Created endpoint for _patient vaccination_.
- Created unit tests testing this functionality.
- Created adapter for StatusEnum (similar to DiseaseEnumAdapter).

[SP-48] Vaccinate patient

---

.gitignore
app/Models/Visits/VaccinationSlotModel.cs
app/Services/Admin/AdminDoctorsService.cs
tests/Unit/Services/Admin/AdminDoctorsServiceTest.cs

Added mail notification when deleting doctor with reserved slots. Mails are grouped by patient so there is no spam.

[SP-154] Add mail notification when deleting doctor with reserved slots

---

app/Controllers/Patient/VaccinationController.cs
app/Helpers/CertificateGenerator.cs
app/Services/Patient/VaccinationService.cs
app/backend.csproj
tests/Helpers/DbHelper.cs
tests/Unit/Helpers/CertificateGeneratorTest.cs
tests/Unit/Services/Admin/AdminPatientsServiceTest.cs
tests/Unit/Services/Patient/VaccinationServiceTest.cs
tests/backend-tests.csproj

- QR code generation using IronBarCode library.
- Add QR code to PDF with vaccination certificates.
_Due to lack of support of standard Image functionality in .NET 6.0, generated QR code is transfered to target PDF file using byte[] array._
I've also created a few unit test to cover Vaccination Certificate functionalities.
- Validating if returned payload in bytes is a PDF file.
- Validating if returned PDF file contains single page.
- Validating if returned page is in A4 format.
- Validating if returned PDF contains patient and vaccination data.
_Due to licensing limitations of IronBarCode, generating QR code during unit testing is treated as usage outside of Visual Studio development environment, which is not covered by free license. It's the reason why QR codes are not generated during …

[SP-149] QR code in vaccination certificate

---

app/Helpers/CertificateGenerator.cs
tests/Unit/Services/Patient/VaccinationServiceTest.cs

Changed QR code generator in order to fix problems in Linux environment.

[SP-250] Fix QR code generator in Linux

---

tests/Integration/Controllers/Patient/VaccinationControllerTests.cs

[] fix discrepancy in tests regarding pdf generation

---

app/Controllers/Patient/VaccinationController.cs
app/Database/DataContext.cs
app/Models/Accounts/PatientModel.cs
app/Postman/IO.postman_collection.json
app/Services/Patient/PatientService.cs
app/Services/Patient/PatientVaccinationService.cs
tests/Integration/Controllers/Patient/VaccinationControllerTests.cs
tests/Unit/Services/Patient/VaccinationServiceTest.cs

added soft delete interface to patient model <3

[SP-163] Patient Account Deletion

---

app/Postman/IO.postman_collection.json
app/Services/Admin/AdminPatientsService.cs

[SP-217] show patients gets params from query

---

app/Dto/Requests/ChangeSlotRequest.cs
tests/Integration/Controllers/Admin/AdminVaccinationController.cs
tests/Integration/Controllers/Doctor/DoctorVaccinationController.cs
tests/Integration/Controllers/Patient/PatientControllerTests.cs
tests/Unit/Services/Admin/AdminVaccinationServiceTest.cs
tests/Unit/Services/Doctor/DoctorVaccinationServiceTest.cs

[SP-218] finishing touches to our ITs

---

app/appsettings.json

Zmian URL w mailu wysyłanych podczas rejestracji na potrzeby frontu

[SP-224] Update registration URL in mail

---

app/Services/Admin/AdminVaccinationService.cs
tests/Unit/Services/Admin/AdminVaccinationServiceTest.cs

Send e-mail to doctor after visit rescheduled by admin.

[SP-228] Doctor notification after visit reschedule
